### ISSUE TITLE
Java 21

### ISSUE THREAD

**Issue by noemisoluri** [biagioT/java-pec-parser#4]
Ciao, dalla documentazione da te fornita ho visto che la libreria non è compatibile con java 21...è possibile avere un nuovo rilascio in cui si risolve questo problema? grazie

**Comment by biagioT** [comment]
la libreria è compatibile con tutte le versioni di Java dalla 1.8 in poi. Hai provato a importarla in un progetto basato su Java 21? Che errori/problemi hai avuto?

**Comment by biagioT** [comment]
-
